### ISSUE TITLE
Remove win32tz.py ?

### ISSUE THREAD

**Issue by da4089** [py-vobject/vobject#34]
The vobject package includes support for obtaining timezone information from the Windows registry, implemented in the win32tz.py file.  It is not imported by any of the other vobject source files: it appears to have been provided basically as a helpful facility if needed by a client application.

This file looks like it has never been ported to Python 3: it imports `_winreg` (renamed to `winreg` in 3.0), and uses `xrange()` (without `six.moves`), for example.

It seems also that `dateutil` provides equivalent functionality from version 2.5.0, which I imagine is much better maintained.

With the change to API v1.0, this file could be removed, with a recommendation to switch to using `dateutil` instead.  This would need an assessment of whether there's actually anything unique about what is implemented, vs. what's in `dateutil`.

**Comment by return42** [comment]
I think it can be removed .. at least this module is not py3 compatible --> https://github.com/return42/vobject/commit/35e3ccf532#diff-16a068e726d774b7e02c57fdbaea48a806343fcbc18e032c9ee5995bf45ced07R1-R5
