### ISSUE TITLE
SyntaxWarning on Python 3.12.3

### ISSUE THREAD

**Issue by iugov** [py-vobject/vobject#46]
Python 3.12 now throws a SyntaxWarning for invalid escape sequences. This will turn into an exception in future Python version, so better to fix soon.

```bash
python3.12/site-packages/vobject/base.py:736: SyntaxWarning: invalid escape sequence '\-'
  patterns['name'] = '[a-zA-Z0-9\-_]+'

python3.12/site-packages/vobject/base.py:1219: SyntaxWarning: invalid escape sequence '\,'
  s = s.replace("\\", "\\\\").replace(";", "\;").replace(",", "\,")
```

**Comment by hodeinavarro** [comment]
I came to this issue recently and did some checking on the repo, you fixed this on https://github.com/py-vobject/vobject/pull/21. The `SyntaxWarning` is fixed on current `master`.
You can close, thank you!

**Comment by da4089** [comment]
Thanks for the report, @iugov.  Glad the _master_ fix worked for you.  I'm planning to make a 0.9.8 release shortly, and this will be included in that.
