### ISSUE TITLE
Should TimezoneComponent.prettyPrint() have default arguments?

### ISSUE THREAD

**Issue by da4089** [py-vobject/vobject#67]
Import from: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849882

Should the `TimezoneComponent.prettyPrint()` function use the same default
values as the equivalent function in other classes?  I discovered that
The method in `TimezoneComponent` have this prototype:

    def prettyPrint(self, level, tabwidth):

While the base class Component have this prototype:

    def prettyPrint(self, level = 0, tabwidth=3):

This made my code fail with this message:

    <VTIMEZONE | <TZID{}Europe/Stockholm>>
    Traceback (most recent call last):
      File "/home/pere/bin/ical-split", line 119, in <module>
        print c.prettyPrint()
    TypeError: prettyPrint() takes exactly 3 arguments (1 given)

This code demonstrates the problem:

    import vobject
    icalstream = open(file)
    components = vobject.readComponents(icalstream, validate=True)
    cal = components.next()
    for c in cal.getChildren():
        print c.prettyPrint()

**Comment by rsb-23** [comment]
This is a `method signature mismatch` issue, and it can be fixed/avoided by using linters.
There can be other methods with this issue and similar issues.
So, I think all can be addressed when linters are added.

**Comment by da4089** [comment]
Will update Debian bug tracker once this fix is on PyPI
